### ISSUE TITLE
writeSettings with 'index = True' gives error for saving the result of blocker.indexAll

### ISSUE THREAD

**Issue by mehrrsaa** [dedupeio/dedupe-examples#79] opened 2018-04-24 15:52 UTC
Hi,

I am trying to minimize runtime for future runs by saving the results of gazetteer_obj.blocker.indexAll(master_data) to a settings file as follows:
with open(filename, 'wb') as new_sf:
        gazetteer_obj.writeSettings(new_sf, index = True)

The issue is that without 'index = True' the result is not saved, and when I set it to True I get the following error when it tries to save the indices: 
'RuntimeError: maximum recursion depth exceeded'

Thank you

**Comment by mehrrsaa** [comment] 2018-04-25 14:35
It seems to be a still open issue (#395) I will look into solutions and if I find any will post here.

**Comment by mehrrsaa** [comment] 2018-04-25 14:37
It seems to be a still open issue. I will look into solutions and if I find any will post here. 
https://github.com/dedupeio/dedupe/issues/395

**Comment by fgregg** [comment] 2018-05-03 14:07
Dupe of dedupeio/dedupe#395

**Closed by fgregg** 2018-05-03 14:07 UTC
